Upgrade to Poetry v1.2.0 and other related cleanup (#6)

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,41 +1,48 @@
 #!/bin/bash
 # Shortcuts for common developer tasks
 
-# Setup the virtual environment via Poetry and install pre-commit hooks
-run_install() {
-
-   # Create and update the virtualenv
-   poetry install -v
-   if [ $? != 0 ]; then
-      exit 1
-   fi
-
-   # Upgrade embedded packages within the virtualenv
-   # This command sometimes returns $?=1 on Windows, even though it succeeds <sigh>
-   poetry run pip install --quiet --upgrade pip wheel setuptools 2>/dev/null
-
-   # Install the pre-commit hooks
-   poetry run pre-commit install 
-   if [ $? != 0 ]; then
-      exit 1
-   fi
-
+disable_keyring() {
+   # Prevent Poetry v1.2.0 from using the Python keyring, which sometimes fails or hangs on Linux
+   # See: https://github.com/python-poetry/poetry/issues/2692#issuecomment-1235683370
+   export PYTHON_KEYRING_BACKEND="keyring.backends.null.Keyring"
 }
 
-# Activate the current Poetry virtual environment
-run_activate() {
-   echo "source "$(dirname $(poetry run which python) 2>/dev/null)/activate""
+enable_keyring() {
+   # We need to unset this for cases where the keyring is required, like publishing
+   unset PYTHON_KEYRING_BACKEND
+}
+
+# Setup the virtual environment via Poetry and install pre-commit hooks
+run_install() {
+   utils/requirements.sh
+   if [ $? != 0 ]; then
+      exit $?
+   fi
 }
 
 # Regenerate the docs/requirements.txt file"
 run_requirements() {
-   poetry export --format=requirements.txt --without-hashes --dev --output=docs/requirements.txt
+   poetry export --format=requirements.txt --without-hashes --with dev --output=docs/requirements.txt
    if [ $? != 0 ]; then
+      echo "*** Failed to export requirements.txt"
       exit 1
+   fi
+
+   # fix the Python version in requirements.txt, which causes readthedocs.io to blow up :( 
+   # annoyingly, BSD sed and GNU sed are not compatible on the syntax for -i
+   # I failed miserably in all attempts to put the sed command (with empty string) into a variable
+   sed --version 2>&1 | grep -iq "GNU sed"
+   if [ $? = 0 ]; then
+      # GNU sed accepts a bare -i and assumes no backup file
+      sed -i 's/python_version >= "3.9"/python_version >= "3.7"/g' docs/requirements.txt
+   else
+      # BSD sed requires you to set an empty backup file extension
+      sed -i "" 's/python_version >= "3.9"/python_version >= "3.7"/g' docs/requirements.txt
    fi
 
    poetry run python utils/dos2unix.py docs/requirements.txt
    if [ $? != 0 ]; then
+      echo "*** Failed to convert requirements.txt to UNIX line endings"
       exit 1
    fi
 }
@@ -297,9 +304,6 @@ case $1 in
    install|setup)
       run_install
       ;;
-   activate)
-      run_activate
-      ;;
    requirements)
       run_requirements
       ;;
@@ -352,7 +356,9 @@ case $1 in
       run_release $*
       ;;
    publish)
+      enable_keyring
       run_publish
+      disable_keyring
       ;;
    *)
       echo ""
@@ -363,7 +369,6 @@ case $1 in
       echo "Usage: run <command>"  
       echo ""
       echo "- run install: Setup the virtualenv via Poetry and install pre-commit hooks"
-      echo "- run activate: Print command needed to activate the Poetry virtualenv"
       echo "- run requirements: Regenerate the docs/requirements.txt file"
       echo "- run format: Run the code formatters"
       echo "- run checks: Run the code checkers"
